
#python run.py --data_set News --missingtype mcar_ --np_seed 0 --torch_seed 0
#python run.py --data_set News --missingtype mcar_ --np_seed 149669 --torch_seed 149669
#python run.py --data_set News --missingtype mcar_ --np_seed 52983 --torch_seed 52983
#python run.py --data_set News --missingtype mnar_ --np_seed 0 --torch_seed 0
#python run.py --data_set News --missingtype mnar_ --np_seed 149669 --torch_seed 149669
#python run.py --data_set News --missingtype mnar_ --np_seed 52983 --torch_seed 52983
#python run.py --data_set News --missingtype mar_ --np_seed 0 --torch_seed 0
#python run.py --data_set News --missingtype mar_ --np_seed 149669 --torch_seed 149669
#python run.py --data_set News --missingtype mar_ --np_seed 52983 --torch_seed 52983
#python run.py --data_set temperature --missingtype mcar_ --np_seed 0 --torch_seed 0
#python run.py --data_set temperature --missingtype mcar_ --np_seed 149669 --torch_seed 149669
#python run.py --data_set temperature --missingtype mcar_ --np_seed 52983 --torch_seed 52983
#python run.py --data_set temperature --missingtype mnar_ --np_seed 0 --torch_seed 0
#python run.py --data_set temperature --missingtype mnar_ --np_seed 149669 --torch_seed 149669
#python run.py --data_set temperature --missingtype mnar_ --np_seed 52983 --torch_seed 52983
#python run.py --data_set temperature --missingtype mar_ --np_seed 0 --torch_seed 0
#python run.py --data_set temperature --missingtype mar_ --np_seed 149669 --torch_seed 149669
#python run.py --data_set temperature --missingtype mar_ --np_seed 52983 --torch_seed 52983
#python run.py --data_set HI --missingtype mcar_ --np_seed 0 --torch_seed 0
#python run.py --data_set HI --missingtype mcar_ --np_seed 149669 --torch_seed 149669
#python run.py --data_set HI --missingtype mcar_ --np_seed 52983 --torch_seed 52983
#python run.py --data_set HI --missingtype mnar_ --np_seed 0 --torch_seed 0
#python run.py --data_set HI --missingtype mnar_ --np_seed 149669 --torch_seed 149669
#python run.py --data_set HI --missingtype mnar_ --np_seed 52983 --torch_seed 52983
#python run.py --data_set HI --missingtype mar_ --np_seed 0 --torch_seed 0
#python run.py --data_set HI --missingtype mar_ --np_seed 149669 --torch_seed 149669
#python run.py --data_set HI --missingtype mar_ --np_seed 52983 --torch_seed 52983
python run.py --data_set gas --missingtype mcar_ --np_seed 0 --torch_seed 0
python run.py --data_set gas --missingtype mcar_ --np_seed 149669 --torch_seed 149669
python run.py --data_set gas --missingtype mcar_ --np_seed 52983 --torch_seed 52983
python run.py --data_set gas --missingtype mnar_ --np_seed 0 --torch_seed 0
python run.py --data_set gas --missingtype mnar_ --np_seed 149669 --torch_seed 149669
python run.py --data_set gas --missingtype mnar_ --np_seed 52983 --torch_seed 52983
#python run.py --data_set gas --missingtype mar_ --np_seed 0 --torch_seed 0
#python run.py --data_set gas --missingtype mar_ --np_seed 149669 --torch_seed 149669
#python run.py --data_set gas --missingtype mar_ --np_seed 52983 --torch_seed 52983